name: Secure Copy Deployment

on:
  push:
    # support either of the 2 common "main" branch names
    branches:
      - master
      - main

env:
  DEPLOY_DIR: /var/www/nickarnold.name/
  SSH_HOST: nickarnold.name
  SSH_USERNAME: github

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build resume (HTML and PDF)
        if: ${{ success() }}
        run: npm run build
        
      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.7
        if: ${{ success() }}
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME}}
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          source: "output/resume.pdf,output/style.css,output/fonts/*.woff2,output/resume.html"
          target: ${{ env.DEPLOY_DIR }}
          # this will remove the 'output' part of the source path on the target
          strip_components: 1
          overwrite: 1
